name: Django CI

on: [push]

jobs:
  run-tests:
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: "Netflix.settings"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install Requirements
      run:
        pip install -r requirements.txt
    - name: Check Directory Structure
      run: |
        
        pwd
        cd Netflix
        ls -l
        pip install setuptools
    - name: Run Tests
      run: python manage.py test
      working-directory: Netflix
